spring.application.name=ecommerce
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# To enabled the H2 Database console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# To create the schema by antotations Entities class
spring.jpa.hibernate.ddl-auto=update

# The scripts data.sql are ALWAYS executed
spring.sql.init.mode=always

# Control by Spring-boot to crate Database
spring.jpa.defer-datasource-initialization=true
